### ISSUE TITLE
UnicodeWidthStr::width produces different results for emoji color variants

### ISSUE THREAD

**Issue by EverlastingBugstopper** [unicode-rs/unicode-width#17]
```rust
#[cfg(test)]
mod tests {
    use unicode_width::UnicodeWidthStr;
    #[test]
    fn emoji_width_are_equal() {
        assert_eq!(UnicodeWidthStr::width("✌🏻"), UnicodeWidthStr::width("✌️"));
    }
}
```

```console
$ cargo test
running 1 test
test tests::it_knows_when_you_are_emoji ... FAILED

failures:

---- tests::it_knows_when_you_are_emoji stdout ----
thread 'tests::it_knows_when_you_are_emoji' panicked at 'assertion failed: `(left == right)`
  left: `3`,
 right: `1`', src/lib.rs:6:9
```

This is... something. Unicode is hard and likely this requires some close following of [UTS #51](https://unicode.org/reports/tr51/) but thought it was worth a report 😄

**Comment by Manishearth** [comment]
Please see the readme, it specifically calls out that a lot of emoji cases don't work. This is implementing UAX 11.

It is not possible to programmatically tell exactly what the rendered width of a set of characters is, because it's font dependent. UAX 11 and unicode-width provide a far simpler concept of width.

**Comment by EverlastingBugstopper** [comment]
Ah - it is right there in the README, staring me in the face.

Thanks @Manishearth 😅
